name: Build and Push Python Data Processor Interpreter

on:
  push:
    branches: [feat/RKT-673-python-interpreters]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --name=python_data_processor --hidden-import=numpy --hidden-import=pandas --onefile python_interpreter.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python_data_processor
          path: dist/python_data_processor

      - name: Create interpreters directory if it doesn't exist
        run: mkdir -p interpreters

      - name: Move built interpreter to interpreters directory
        run: mv dist/python_data_processor interpreters/

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          git add interpreters
          git commit -m "Update interpreters" || echo "No changes to commit"
          git push origin $current_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
